### ISSUE TITLE
In algoirthms implement a quickSort instead of selectionSort

### ISSUE THREAD

**Issue by John4064** [John4064/text-analysis#11]

**Comment by daredevil3435** [comment]
I am newbie in open source contribution but I am very much interested in this issue. can you please assign this issue to me?

**Comment by Indira-kumar** [comment]
Good Evening @John4064 , I am a newbie in open-source contribution, but I am well versed in C++. So could you please assign this issue to me?

**Comment by angelinakap2** [comment]
Hello @John4064, I have some experience in coding in C++ and am interested in open-source contribution. Could I be assigned to this code as a participant?

**Comment by cboyce376** [comment]
Hey @John4064,

Isn't c++ std::sort already implementing a version of quicksort?

According to [this page](https://www.geeksforgeeks.org/internal-details-of-stdsort-in-c/) std::sort implements introsort, which is implements quicksort and other algorithms to have O(nlog(n)) worst case performance.

**Comment by John4064** [comment]
@cboyce376 I created this issue while using a different sorting solution and never went back and cleaned up and closed it. Thank you for bringing to my attn!
